version: "3.7"
networks:
  app-micro-service:
    driver: bridge
services:
  db-postgres:
    image: 'postgres:alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=core_banner
    volumes:
      - '.docker/postgres_data:/var/lib/postgresql/data'
    networks:
      - app-micro-service

  db-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: banners
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      TZ: America/Sao_Paulo
    cap_add:
      - SYS_NICE
    volumes:
      - .docker/mysql_data:/var/lib/mysql
    networks:
      - app-micro-service

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
          - .docker/rabbitmq_data:/var/lib/rabbitmq/
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin

volumes:
  postgres_data:
  mysql_data: