version: "3.7"
networks:
  app-micro-service:
    driver: bridge
services:
  db-postgres:
    image: 'postgres:alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=core
      # - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # - '.docker/postgres_data:/data/postgres'
      - '.docker/postgres_data:/var/lib/postgresql/data'
    networks:
      - app-micro-service

  db-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: banners
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      TZ: America/Sao_Paulo
    cap_add:
      - SYS_NICE
    volumes:
      - .docker/mysql_data:/var/lib/mysql
    networks:
      - app-micro-service

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-micro-service
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - .docker/zookeeper_data:/bitnami
      
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-micro-service
    volumes:
      - .docker/kafka_data:/bitnami

volumes:
  postgres_data:
  mysql_data: